## 00. PyTorch Fundamentals

Base notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
print(torch.__version__)

1.13.1+cu116


## Intro to Tensors
### Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [2,5,7],
                        [2,8,4]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 5, 7],
         [2, 8, 4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Ramdom tensors

Random tensors are important because the way many neural nets learn is that they start with tensors full of random numbers and then adjust those random nums to better represent the data.

`Start with random nums -> look at data -> update random nums -> look at data -> update random nums`

In [ ]:
# Create random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2700, 0.6220, 0.1517, 0.8197],
        [0.0500, 0.6994, 0.2344, 0.6086],
        [0.5052, 0.3316, 0.0643, 0.3326]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # Datatype (e.g. float32, float64...)
                               device=None, # GPU(cuda) or CPU 
                               requires_grad=False) 
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

## Tensor attributes

In [ ]:
some_tensor = torch.rand(3,4)

In [ ]:
print(f"type    {some_tensor.dtype}")
print(f"shape   {some_tensor.shape}")
print(f"device  {some_tensor.device}")

type    torch.float32
shape   torch.Size([3, 4])
device  cpu


### Managing Tensors (tensor operations)
Tensors operations include:
- Addition
- Substruction
- Multiplication (elemet-wise)
- Division
- Matrix multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

### Matrix manipulation

In [ ]:
import torch
t = torch.arange(1., 10.)
t, t.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add new dimention
t_reshaped = t.reshape(3,3)
t_reshaped, t_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]), torch.Size([3, 3]))

In [ ]:
# Change view
z = t.view(1,9)
z, z.shape, t, t.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [ ]:
# Changing view changes initial tensor
z[:, 0] = 5
t, t.shape, z, z.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]))

In [ ]:
# Stack tensors on top of each other
t_stacked = torch.stack([t_reshaped, t_reshaped], dim=0)
t_stacked

tensor([[[5., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[5., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [ ]:
# Remove size-1 dimentions
ts = torch.zeros(2,1,2)
ts.squeeze()

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
x = torch.tensor([1, 2, 3, 4])
x.shape, torch.unsqueeze(x, 0).shape

(torch.Size([4]), torch.Size([1, 4]))

In [ ]:
x.reshape(4, 1, 1)

tensor([[[1]],

        [[2]],

        [[3]],

        [[4]]])

In [ ]:
x = torch.randn(224,224,3)
x.permute(2,0,1)

tensor([[[-6.1268e-02, -1.6475e-02, -2.5488e-01,  ..., -3.1747e-01,
           2.1612e+00, -1.3357e-01],
         [ 1.9294e-01, -1.0609e+00,  1.2200e-01,  ...,  4.6801e-01,
           7.2286e-01,  1.2985e+00],
         [-4.3286e-01, -2.5857e-01,  7.7695e-01,  ..., -8.6042e-01,
           7.5482e-01,  9.0167e-01],
         ...,
         [ 3.3243e-01,  7.6694e-04, -8.2722e-01,  ...,  1.3185e+00,
           1.4218e+00,  1.9336e-01],
         [-6.9871e-01, -6.6396e-01,  7.9267e-01,  ..., -1.4809e+00,
           5.2453e-01,  1.1676e-02],
         [-1.2046e+00,  4.4891e-02,  1.2077e+00,  ..., -1.6656e+00,
           3.3930e-01, -8.7529e-01]],

        [[-1.1944e+00, -1.6220e+00, -1.7995e-01,  ...,  6.2433e-01,
          -4.8338e-02, -7.1653e-01],
         [-1.2232e+00,  9.0054e-01,  4.0770e-01,  ..., -1.4204e+00,
           1.6915e+00,  5.5642e-01],
         [-5.2279e-01,  8.4389e-01, -9.3188e-01,  ...,  8.7192e-01,
          -7.9362e-02,  3.5281e-01],
         ...,
         [ 1.7436e+00, -1

In [ ]:
torch.permute(x, (2,0,1))

tensor([[[-6.1268e-02, -1.6475e-02, -2.5488e-01,  ..., -3.1747e-01,
           2.1612e+00, -1.3357e-01],
         [ 1.9294e-01, -1.0609e+00,  1.2200e-01,  ...,  4.6801e-01,
           7.2286e-01,  1.2985e+00],
         [-4.3286e-01, -2.5857e-01,  7.7695e-01,  ..., -8.6042e-01,
           7.5482e-01,  9.0167e-01],
         ...,
         [ 3.3243e-01,  7.6694e-04, -8.2722e-01,  ...,  1.3185e+00,
           1.4218e+00,  1.9336e-01],
         [-6.9871e-01, -6.6396e-01,  7.9267e-01,  ..., -1.4809e+00,
           5.2453e-01,  1.1676e-02],
         [-1.2046e+00,  4.4891e-02,  1.2077e+00,  ..., -1.6656e+00,
           3.3930e-01, -8.7529e-01]],

        [[-1.1944e+00, -1.6220e+00, -1.7995e-01,  ...,  6.2433e-01,
          -4.8338e-02, -7.1653e-01],
         [-1.2232e+00,  9.0054e-01,  4.0770e-01,  ..., -1.4204e+00,
           1.6915e+00,  5.5642e-01],
         [-5.2279e-01,  8.4389e-01, -9.3188e-01,  ...,  8.7192e-01,
          -7.9362e-02,  3.5281e-01],
         ...,
         [ 1.7436e+00, -1

In [ ]:
!nvidia-smi

Thu Jan 19 10:06:50 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P0    29W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch

In [ ]:
rand_tensor = torch.rand((7,7))
rand_tensor

tensor([[0.3792, 0.9040, 0.3748, 0.0167, 0.7724, 0.9108, 0.3113],
        [0.6200, 0.5944, 0.1577, 0.3543, 0.2093, 0.2158, 0.6767],
        [0.0239, 0.2131, 0.3459, 0.1060, 0.2008, 0.0306, 0.1767],
        [0.3715, 0.3612, 0.9215, 0.5885, 0.0274, 0.9469, 0.6401],
        [0.0960, 0.6852, 0.5605, 0.0675, 0.0514, 0.7620, 0.1603],
        [0.0613, 0.0883, 0.4154, 0.6759, 0.4157, 0.0151, 0.2094],
        [0.3263, 0.0592, 0.2108, 0.1832, 0.8947, 0.8777, 0.4431]])

In [ ]:
xy_tensor = torch.rand((1,7))
xy_tensor

tensor([[0.7159, 0.0547, 0.2142, 0.2767, 0.4100, 0.8361, 0.1028]])

In [ ]:
torch.matmul(rand_tensor, xy_tensor.transpose(1,0))

tensor([[1.5162],
        [0.9441],
        [0.2583],
        [1.5148],
        [0.9197],
        [0.5294],
        [1.4790]])

In [1]:
import torch
from torch import nn # nn modules
import matplotlib.pyplot as plt

# Check PyTorch version
torch.__version__

'1.13.1+cu116'

In [4]:
# GENERATING DATA
weight = 0.7
bias = 0.3

# Create data
start = 0
end = 1
step = 0.02
X = torch.arange(start, end, step).unsqueeze(dim=1) #
y = weight * X + bias
X[:10], y[:10]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]), tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))